backend:
  name: git-gateway
  branch: main 
media_folder: "/images"
# Media files will be stored in the repo under static/images/uploads
public_folder: "/images"
collections:
 - name: "index"
   label: "index page"
   folder: "images"
   create: true
   slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
   files:
      - file: index.html
        label: Index Page
        name: index
   fields:
      - { name: title, label: Title, widget: string }
      - { name: content, label: Content, widget: text }
      - { name: link, label: Link, widget: string }