backend:
  name: git-gateway
  branch: main 
media_folder: "/images"
# Media files will be stored in the repo under static/images/uploads
collections:
  - name: 'data'
    label: 'Website Data'
    files:
      - file: 'data.json'
        name: 'data'
        label: 'Data'
        files: 'data.json'
        create : true
        fields:
          - { name: 'title', label: 'Title', widget: 'string' }
          - { name: 'description', label: 'Description', widget: 'text' }
          - { name: 'contact', label: 'Contact', widget: 'object', fields: [
              { name: 'email', label: 'Email', widget: 'string' },
              { name: 'phone', label: 'Phone', widget: 'string' }
            ] }