backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
  media_folder : "images"

  collections:
  - name: index
    label: Index Page
    files:
      - file: index.html
        label: Index Page
        name: index
        fields:
          - { name: title, label: Title, widget: string }
          - { name: content, label: Content, widget: text }
          - { name: link, label: Link, widget: string }