backend:
  name: git-gateway
  branch: main 
media_folder: "/images"
# Media files will be stored in the repo under static/images/uploads
public_folder: "/images"
collections:
 - name: pages
   label: pages
   folder: "/index.html"      
   files:
      - file: index.html
        label: Index 
        name: index
        fields:
          - { name: title, label: Title, widget: string }
          - { name: content, label: Content, widget: text }
          - { name: link, label: Link, widget: string }